#! /bin/sh

if [ -z "$PACKAGES_FILE" ]; then
  PACKAGES_FILE="$CONFDIR/packages"
fi

packages_loaded=

printpackage()
{
  echo "Package read:"
  echo "  Package: $PACKAGE"
  echo "  Package flags: $PACKAGE_FLAGS"
}

resetPackages()
{
  packages_loaded=
  if ! [ -f "$PACKAGES_FILE" ]; then
    logprint "Package file does not exist"
    return 1
  fi
}

getPackage()
{
  if [ "$packages_loaded" = "" ]; then
    if ! exec 4<$PACKAGES_FILE; then
      return 1
    fi
    packages_loaded=1
    echo "$PACKAGES_FILE loaded"
  fi

  export PACKAGE=
  export PACKAGE_FLAGS=

  while <&4 read -r REPLY; do
    REPLY=${REPLY##\#*}
    if [ -z "$REPLY" ]; then
      if ! [ -z "$PACKAGE" ]; then
        printpackage
	return 0
      fi
      continue;
    fi

    if [ -z "$PACKAGE" ]; then
      export PACKAGE=$REPLY;
    elif [ -z "$PACKAGE_FLAGS" ]; then
      export PACKAGE_FLAGS=$REPLY;
    else
      echo "Unexpected line: $REPLY"
      return 1
    fi
  done

  if ! [ -z "$PACKAGE" ]; then
    printpackage
    return 0
  fi

  return 1
}

